AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  draw-graph

  Sample SAM Template for draw-graph

Globals:
  Function:
    Timeout: 60
    MemorySize: 1024

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId: 
              Ref: ApiGatewayApi

  FileUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: old_func/
      Handler: upload.lambda_handler
      Runtime: python3.9
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        FileUpload:
          Type: Api
          Properties:
            Path: /upload
            Method: post
            RestApiId: 
              Ref: ApiGatewayApi

  PlotCsvFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: old_func/
      Handler: plot_csv.lambda_handler
      Runtime: python3.9
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        PlotCsv:
          Type: Api
          Properties:
            Path: /plot_csv
            Method: post
            RestApiId: 
              Ref: ApiGatewayApi

  UploadPlotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: plot_data/
      Handler: upload_plot.lambda_handler
      Runtime: python3.9
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        PlotCsv:
          Type: Api
          Properties:
            Path: /upload_plot
            Method: post
            RestApiId: 
              Ref: ApiGatewayApi

  OverlapFrameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: plot_data/
      Handler: overlap_frame.lambda_handler
      Runtime: python3.9
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        PlotCsv:
          Type: Api
          Properties:
            Path: /overlap_frame
            Method: post
            RestApiId: 
              Ref: ApiGatewayApi

  DataListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: plot_data/
      Handler: data_list.lambda_handler
      Runtime: python3.9
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        DataListPost:
          Type: Api
          Properties:
            Path: /data_list
            Method: post
            RestApiId: 
              Ref: ApiGatewayApi
        DataListPut:
          Type: Api
          Properties:
            Path: /data_list
            Method: put
            RestApiId: 
              Ref: ApiGatewayApi

  DownloadFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: plot_data/
      Handler: download_file.lambda_handler
      Runtime: python3.9
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        FileUpload:
          Type: Api
          Properties:
            Path: /download_file
            Method: get
            RestApiId: 
              Ref: ApiGatewayApi

  DownloadPlotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: plot_data/
      Handler: download_plot.lambda_handler
      Runtime: python3.9
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Events:
        DownloadPlot:
          Type: Api
          Properties:
            Path: /download_plot
            Method: post
            RestApiId: 
              Ref: ApiGatewayApi
  

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,HEAD,PATCH,OPTION'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
